version: 2
jobs:
  build:
    branches:
      only:
        - gh-page
    docker:
      - image: circleci/node:7.10
    
    working_directory: ~/blog

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install --save

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: node_modules/.bin/hexo-cli deploy --generate

      - add_ssh_keys:
          fingerprints:
            - "08:1b:c0:8c:b3:c1:6b:24:17:8d:7c:3f:a1:a4:66:a9"

    

    