version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.14.0-stretch
    
    working_directory: ~/blog

    steps:
      - checkout
      - run: mkdir -p themes
      - run: git clone https://github.com/noirgif/tranquilpeak themes/tranquilpeak 

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install --save
      - run: 
          name: Keyscan hack
          command:  ssh-keyscan -H mjol.nir.moe >> ~/.ssh/known_hosts

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo apt install -y rsync
      - run: git config --global user.email "nomaru@outlook.com"
      - run: git config --global user.name "noirgif(circleci)"
      - add_ssh_keys:
          fingerprints:
            - "08:1b:c0:8c:b3:c1:6b:24:17:8d:7c:3f:a1:a4:66:a9"
      - run: node_modules/.bin/hexo deploy --generate


    

    
