version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cimg/node:current
    
    working_directory: ~/blog

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install --save
      - run: cd themes/tranquilpeak && npm install --save

      - save_cache:
          paths:
            - node_modules
            - themes/tranquilpeak/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: git config --global user.email "nomaru@outlook.com"
      - run: git config --global user.name "noirgif(circleci)"

      - run: sed -i "s/<ALGOLIA_ADMIN_API_KEY>/$ALGOLIA_ADMIN_API_KEY/" _config.yml

      - run: cd themes/tranquilpeak && npm run prod
      - run: node_modules/.bin/hexo generate
      - run: 
          name: add other files, not generated by hexo
          command: mv others/* public/
      - add_ssh_keys:
          fingerprints:
            - "08:1b:c0:8c:b3:c1:6b:24:17:8d:7c:3f:a1:a4:66:a9"
      - run: node_modules/.bin/hexo deploy
