const BASE=window.__SITE_BASE__||'';
const siteUrl=p=>BASE+p;
function prefixLinks(root){for(const el of root.querySelectorAll('[href],[src],[data-full],[data-preview]'))for(const attr of ['href','src','data-full','data-preview']){const value=el.getAttribute(attr);if(value?.startsWith('/')&&!value.startsWith('//')&&!(BASE&&value.startsWith(BASE+'/')))el.setAttribute(attr,siteUrl(value));}}
const main=document.querySelector('#content'), statusEl=document.querySelector('#status'), progress=document.querySelector('#progress');
const menuButton=document.querySelector('#mobile-menu-toggle');
function closeMobileMenu(){document.body.classList.remove('mobile-menu-open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open navigation menu');}
menuButton.addEventListener('click',()=>{const open=document.body.classList.toggle('mobile-menu-open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('mobile-menu-open')){closeMobileMenu();menuButton.focus();}});
let records=[],routes={},controller=null,sequence=0,ready;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=p=>decodeURI(BASE&&p.startsWith(BASE+'/')?p.slice(BASE.length):p===BASE?'/':p).replace(/\/index\.html$/,'/').replace(/\/$/,'')||'/';
function setReadingMode(path){closeMobileMenu();const post=path.startsWith('/posts/'),sidebar=document.querySelector('.sidebar');if(post&&sidebar.contains(document.activeElement))document.querySelector('#breadcrumb').focus({preventScroll:true});document.body.classList.toggle('post-view',post);sidebar.inert=post;if(post)sidebar.setAttribute('aria-hidden','true');else sidebar.removeAttribute('aria-hidden');}
const date=s=>s?new Date(s).toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'}):'';
const posts=()=>records.filter(r=>r.path.startsWith('/posts/'));
function element(html,cls=''){const d=document.createElement('div');d.className='reveal '+cls;d.innerHTML=html;prefixLinks(d);main.append(d);enhanceImages(d);return d}
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){observer.unobserve(e.target);sharpen(e.target)}},{rootMargin:'250px'});
async function sharpen(img){if(!img.dataset.full)return;const url=img.dataset.full;delete img.dataset.full;try{const full=new Image();full.src=url;await full.decode();if(!img.isConnected)return;img.src=url;img.classList.add('sharp')}catch{img.classList.add('sharp');img.alt+=' (full image unavailable)'}}
function enhanceImages(root){for(const img of root.querySelectorAll('img[data-full]')){if(img.dataset.preview){img.src=img.dataset.preview;img.classList.remove('sharp')}observer.observe(img)}}
function heading(title,sub='',kicker='JOURNAL'){element(`<div class="section-heading"><h1 tabindex="-1">${escape(title)}</h1></div>`)}
function row(p){return `<div class="row"><span class="date">${escape(date(p.date))}</span><a href="${escape(p.path)}">${escape(p.title)}</a></div>`}
function highlighted(text,q){text=String(text);let result='',offset=0,index;while((index=text.toLowerCase().indexOf(q,offset))!==-1){result+=escape(text.slice(offset,index))+'<mark>'+escape(text.slice(index,index+q.length))+'</mark>';offset=index+q.length}return result+escape(text.slice(offset))}
function searchResult(p,q){const text=(p.paragraphs||[]).find(t=>t.toLowerCase().includes(q))||(p.searchText?.toLowerCase().includes(q)?p.searchText:'');let snippet='';if(text){const index=text.toLowerCase().indexOf(q),start=Math.max(0,index-70),end=Math.min(text.length,Math.max(start+210,index+q.length));snippet=(start?'…':'')+text.slice(start,end)+(end<text.length?'…':'')}const tags=p.tags.filter(t=>t.toLowerCase().includes(q));const category=p.category.toLowerCase().includes(q)?p.category:'';return `<article class="search-result"><div class="row"><time class="date">${escape(date(p.date))}</time><a href="${escape(p.path)}">${highlighted(p.title,q)}</a></div>${snippet?`<p class="search-snippet">${highlighted(snippet,q)}</p>`:''}${tags.length||category?`<div class="search-tags">${tags.map(t=>`<a href="/tags/${encodeURIComponent(t)}">#${highlighted(t,q)}</a>`).join(' ')}${category?`<a href="/categories/${encodeURIComponent(category)}">${highlighted(category,q)}</a>`:''}</div>`:''}</article>`}
function card(p){return `<article class="post-card"><div class="meta"><time>${escape(date(p.date))}</time><span>·</span><a class="category" href="/categories/${encodeURIComponent(p.category)}">${escape(p.category)}</a></div><h2><a href="${escape(p.path)}">${escape(p.title)}</a></h2>${p.image?`<a href="${escape(p.path)}" class="preview-images"><img class="progressive" src="${p.image}" data-full="${p.image.replace('-tiny.jpg','.jpg')}" alt="${escape(p.title)}" loading="lazy"></a>`:''}<p>${escape(p.excerpt.slice(0,165))}…</p></article>`}
async function streamPost(path,signal,id){const response=await fetch(siteUrl(`/data/${routes[path]}.ndjson`),{signal});if(!response.ok)throw Error('This entry could not be loaded.');const reader=response.body.getReader(), decoder=new TextDecoder();let buffer='',head=false;
 function line(s){if(!s.trim()||id!==sequence)return;const data=JSON.parse(s);if(!head){head=true;document.title=data.title+' · Goddess Unknown';element(`<div class="article-head"><div class="meta"><time>${escape(date(data.date))}</time>${data.category?`<span>·</span><a class="category" href="/categories/${encodeURIComponent(data.category)}">${escape(data.category)}</a>`:''}</div><h1 tabindex="-1">${escape(data.title)}</h1></div>`)}else element(data.html,data.kind==='related'?'':'article-body')}
 while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let n;while((n=buffer.indexOf('\n'))>=0){line(buffer.slice(0,n));buffer=buffer.slice(n+1)}if(done){line(buffer);break}}
}
async function render(path,signal,id){await ready;if(signal.aborted)return;document.title='Goddess Unknown';const all=posts();
 if(routes[path])return streamPost(path,signal,id);
 if(path==='/'){all.slice(0,window.__POSTS_PER_PAGE__||8).forEach(p=>element(card(p)));element('<a class="chip" href="/all-archives">Browse all entries</a>');return}
 if(path==='/search'){const wrap=element('<h1 class="sr-only" tabindex="-1">Search</h1><label class="sr-only" for="query">Search titles, text, or tags</label><input id="query" class="search-input" type="search" placeholder="Type a word or phrase to search titles, text, or tags" autocomplete="off"><div id="results" aria-live="polite"></div>');const input=wrap.querySelector('input'),results=wrap.querySelector('#results');const search=()=>{const q=input.value.trim().toLowerCase(),list=q?all.filter(p=>[p.title,p.searchText||p.excerpt,p.category,...p.tags].some(text=>text.toLowerCase().includes(q))):[];results.innerHTML=list.length?list.map(p=>searchResult(p,q)).join(''):q?'<p class="empty">No entries found. Try another word.</p>':'';prefixLinks(results)};input.addEventListener('input',search);search();return}
 if(path==='/all-archives'){let year='';for(const p of all){const y=p.date.slice(0,4)||'Undated';if(y!==year){year=y;element(`<h2 class="year-title">${escape(y)}</h2>`)}element(row(p))}return}
 if(path==='/all-categories'||path==='/all-tags'){const kind=path==='/all-tags'?'tags':'categories';const counts={};for(const p of all)for(const k of kind==='tags'?p.tags:[p.category])counts[k]=(counts[k]||0)+1;element(`<div class="chips">${Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,n])=>`<a class="chip" href="/${kind}/${encodeURIComponent(k)}">${escape(k)}<small>${n}</small></a>`).join('')}</div>`);if(!Object.keys(counts).length)element('<p class="empty">No tags in this journal yet.</p>');return}
 if(/^\/(categories|tags)\//.test(path)){const [,kind,...rest]=path.split('/'),name=decodeURIComponent(rest.join('/'));const list=all.filter(p=>kind==='tags'?p.tags.includes(name):p.category===name);heading(name,`${list.length} entries`,kind.toUpperCase());list.forEach(p=>element(row(p)));if(!list.length)element('<p class="empty">No entries found.</p>');return}
 heading('This page has wandered off.','','404');element('<p>The entry could not be found.</p><a class="chip" href="/">Return to the journal</a>');
}
function saveScroll(){history.replaceState({...history.state,scroll:window.scrollY},'')}
async function navigate(raw,{push=true,restore=null}={}){const url=new URL(raw,location.origin),path=normalize(url.pathname);setReadingMode(path);const id=++sequence;controller?.abort();controller=new AbortController();observer.disconnect();if(push)saveScroll();main.replaceChildren();main.setAttribute('aria-busy','true');statusEl.textContent='Loading…';progress.classList.add('busy');if(push)history.pushState({scroll:0},'',url.pathname+url.search+url.hash);window.scrollTo({top:0,behavior:'instant'});document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===path;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.querySelector('#breadcrumb').textContent=path==='/'?'Journal':path.startsWith('/posts/')?'Journal / Entry':path.includes('categories')?'Journal / Categories':path.includes('tags')?'Journal / Tags':path.includes('archives')?'Journal / Archives':path==='/search'?'Journal / Search':path==='/about'?'Journal / About':'Journal / Links';
 try{await render(path,controller.signal,id);if(id!==sequence)return;statusEl.textContent='';if(push)main.querySelector('h1')?.focus({preventScroll:true});if(restore!==null)requestAnimationFrame(()=>window.scrollTo({top:restore,behavior:'instant'}));else if(url.hash)document.getElementById(decodeURIComponent(url.hash.slice(1)))?.scrollIntoView();}
 catch(e){if(e.name==='AbortError'||id!==sequence)return;statusEl.textContent='';element('<h1>Couldn’t load this page.</h1><p>Please try again.</p><button class="retry">Retry</button>');main.querySelector('.retry').onclick=()=>navigate(raw,{push:false});}
 finally{if(id===sequence){main.setAttribute('aria-busy','false');progress.classList.remove('busy')}}
}
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||a.target||a.hasAttribute('download'))return;const url=new URL(a.href);if(url.origin!==location.origin||normalize(url.pathname).startsWith('/media/'))return;if(url.pathname===location.pathname&&url.hash){return}e.preventDefault();navigate(url.href)});
history.scrollRestoration='manual';window.addEventListener('popstate',e=>navigate(location.href,{push:false,restore:e.state?.scroll??0}));let scrollTimer;window.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(saveScroll,100)},{passive:true});
let snowTimer;document.querySelector('#snow').onclick=()=>{const b=document.querySelector('#snow');if(snowTimer){clearInterval(snowTimer);snowTimer=null;b.setAttribute('aria-pressed','false');return}b.setAttribute('aria-pressed','true');if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;snowTimer=setInterval(()=>{const f=document.createElement('span');f.className='snowflake';f.textContent='❄';f.style.left=Math.random()*34+'vw';f.style.opacity=.25+Math.random()*.5;f.style.fontSize=8+Math.random()*10+'px';f.style.animationDuration=6+Math.random()*7+'s';document.body.append(f);f.onanimationend=()=>f.remove()},350)};
setReadingMode(normalize(location.pathname));
ready=Promise.all(['/data/records.json','/data/routes.json','/data/assets.json'].map(async u=>{const r=await fetch(siteUrl(u));if(!r.ok)throw Error('Journal unavailable');return r.json()})).then(([r,t,a])=>{records=r;routes=t;document.querySelector('.cover').src=siteUrl(a.cover);document.querySelector('.avatar').src=siteUrl(a.avatar)});if(main.dataset.prebuilt&&normalize(location.pathname)!=='/search'){ready.then(()=>enhanceImages(main)).catch(()=>{statusEl.textContent='Navigation is unavailable. Refresh the page to try again.'});}else navigate(location.href,{push:false});
